name: Build documentation
on:
  push:
    branches:
      - master
      
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Generate HTML from Markdown
      uses: ldeluigi/markdown-docs@latest
      with:
        src: /documentation
        dst: /generated
        title: Social Drone UA
        language: uk